sudo: false

language: elixir

matrix:
  include:
    - elixir: 1.8
      otp_release: 21.1
    - elixir: 1.8
      otp_release: 20.1
    - elixir: 1.7
      otp_release: '20.1'
    - elixir: 1.4
      otp_release: '19.1'

cache:
  directories:
    - .plts

before_script:
  - mkdir -p .plts
  - "[[ -f .plts/local.plt ]] || mix dialyzer --plt"

script:
  - mix credo --strict
  - mix format --check-formatted --dry-run
  - mix dialyzer --halt-exit-status
  - mix test
